# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .catalog_modifier import CatalogModifierParams
from .catalog_object_base import CatalogObjectBaseParams


class CatalogObjectModifierParams(CatalogObjectBaseParams):
    modifier_data: typing_extensions.NotRequired[CatalogModifierParams]
    """
    Structured data for a `CatalogModifier`, set for CatalogObjects of type `MODIFIER`.
    """
