# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing


class CatalogModifierOverrideParams(typing_extensions.TypedDict):
    """
    Options to control how to override the default behavior of the specified modifier.
    """

    modifier_id: str
    """
    The ID of the `CatalogModifier` whose default behavior is being overridden.
    """

    on_by_default: typing_extensions.NotRequired[typing.Optional[bool]]
    """
    If `true`, this `CatalogModifier` should be selected by default for this `CatalogItem`.
    """
