# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .dispute_evidence import DisputeEvidenceParams
from .error import ErrorParams


class CreateDisputeEvidenceFileResponseParams(typing_extensions.TypedDict):
    """
    Defines the fields in a `CreateDisputeEvidenceFile` response.
    """

    errors: typing_extensions.NotRequired[typing.Sequence[ErrorParams]]
    """
    Any errors that occurred during the request.
    """

    evidence: typing_extensions.NotRequired[DisputeEvidenceParams]
    """
    The metadata of the newly uploaded dispute evidence.
    """
