# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .device_code_paired_event_object import DeviceCodePairedEventObjectParams


class DeviceCodePairedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the paired object’s type, `"device_code"`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the paired device code.
    """

    object: typing_extensions.NotRequired[DeviceCodePairedEventObjectParams]
    """
    An object containing the paired device code.
    """
