# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .dispute_state_updated_event_object import DisputeStateUpdatedEventObjectParams


class DisputeStateUpdatedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the affected dispute's type.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the affected dispute.
    """

    object: typing_extensions.NotRequired[DisputeStateUpdatedEventObjectParams]
    """
    An object containing fields and values relevant to the event.
    """
