# This file was auto-generated by Fern from our API Definition.

import typing_extensions
import typing_extensions
import typing
from .error import ErrorParams
from .customer_segment import CustomerSegmentParams


class GetCustomerSegmentResponseParams(typing_extensions.TypedDict):
    """
    Defines the fields that are included in the response body for requests to the `RetrieveCustomerSegment` endpoint.

    Either `errors` or `segment` is present in a given response (never both).
    """

    errors: typing_extensions.NotRequired[typing.Sequence[ErrorParams]]
    """
    Any errors that occurred during the request.
    """

    segment: typing_extensions.NotRequired[CustomerSegmentParams]
    """
    The retrieved customer segment.
    """
