# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .error import ErrorParams
from .order import OrderParams


class GetOrderResponseParams(typing_extensions.TypedDict):
    order: typing_extensions.NotRequired[OrderParams]
    """
    The requested order.
    """

    errors: typing_extensions.NotRequired[typing.Sequence[ErrorParams]]
    """
    Any errors that occurred during the request.
    """
