# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .gift_card import GiftCardParams


class GiftCardUpdatedEventObjectParams(typing_extensions.TypedDict):
    """
    An object that contains the gift card associated with a `gift_card.updated` event.
    """

    gift_card: typing_extensions.NotRequired[GiftCardParams]
    """
    The gift card with the updated `balance_money`, `state`, or `customer_ids` field. 
    Some events can affect both `balance_money` and `state`.
    """
