# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .inventory_count_updated_event_object import InventoryCountUpdatedEventObjectParams


class InventoryCountUpdatedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the affected object’s type. For this event, the value is `inventory_counts`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the affected object.
    """

    object: typing_extensions.NotRequired[InventoryCountUpdatedEventObjectParams]
    """
    An object containing fields and values relevant to the event. Is absent if affected object was deleted.
    """
