# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .inventory_count import InventoryCountParams


class InventoryCountUpdatedEventObjectParams(typing_extensions.TypedDict):
    inventory_counts: typing_extensions.NotRequired[typing.Optional[typing.Sequence[InventoryCountParams]]]
    """
    The inventory counts.
    """
