# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .invoice_refunded_event_object import InvoiceRefundedEventObjectParams


class InvoiceRefundedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the affected object’s type, `"invoice"`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the affected invoice.
    """

    object: typing_extensions.NotRequired[InvoiceRefundedEventObjectParams]
    """
    An object containing the refunded invoice.
    """
