# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .shift import ShiftParams


class LaborShiftCreatedEventObjectParams(typing_extensions.TypedDict):
    shift: typing_extensions.NotRequired[ShiftParams]
    """
    The new `Shift`.
    """
