# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .labor_shift_created_event_data import LaborShiftCreatedEventDataParams


class LaborShiftCreatedEventParams(typing_extensions.TypedDict):
    """
    Published when a worker starts a [Shift](entity:Shift).

    Deprecated at Square API version 2025-05-21. Replaced by `labor.timecard.created`.
    """

    merchant_id: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The ID of the merchant associated with the event.
    """

    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The type of event. For this event, the value is `labor.shift.created`.
    """

    event_id: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The unique ID for the event.
    """

    created_at: typing_extensions.NotRequired[str]
    """
    The timestamp of when the event was created, in RFC 3339 format.
    """

    data: typing_extensions.NotRequired[LaborShiftCreatedEventDataParams]
    """
    The data associated with the event.
    """
