# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .load_result import LoadResultParams


class LoadResponseParams(typing_extensions.TypedDict):
    pivot_query: typing_extensions.NotRequired[
        typing_extensions.Annotated[typing.Dict[str, typing.Any], FieldMetadata(alias="pivotQuery")]
    ]
    slow_query: typing_extensions.NotRequired[typing_extensions.Annotated[bool, FieldMetadata(alias="slowQuery")]]
    query_type: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="queryType")]]
    results: typing.Sequence[LoadResultParams]
