# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class LoyaltyEventAdjustPointsParams(typing_extensions.TypedDict):
    """
    Provides metadata when the event `type` is `ADJUST_POINTS`.
    """

    loyalty_program_id: typing_extensions.NotRequired[str]
    """
    The Square-assigned ID of the [loyalty program](entity:LoyaltyProgram).
    """

    points: int
    """
    The number of points added or removed.
    """

    reason: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The reason for the adjustment of points.
    """
