# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .loyalty_account_created_event_object import LoyaltyAccountCreatedEventObjectParams


class LoyaltyAccountCreatedEventDataParams(typing_extensions.TypedDict):
    """
    The data associated with a `loyalty.account.created` event.
    """

    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The type of object affected by the event. For this event, the value is `loyalty_account`.
    """

    id: typing_extensions.NotRequired[str]
    """
    The ID of the affected loyalty account.
    """

    object: typing_extensions.NotRequired[LoyaltyAccountCreatedEventObjectParams]
    """
    An object that contains the new loyalty account.
    """
