# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .custom_attribute_definition_event_data import CustomAttributeDefinitionEventDataParams


class MerchantCustomAttributeDefinitionOwnedCreatedEventParams(typing_extensions.TypedDict):
    """
    Published when a merchant [custom attribute definition](entity:CustomAttributeDefinition)
    is created by the subscribing application. Subscribe to this event to be notified
    when your application creates a merchant custom attribute definition.
    """

    merchant_id: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The ID of the seller associated with the event that triggered the event notification.
    """

    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    The type of this event. The value is `"merchant.custom_attribute_definition.owned.created"`.
    """

    event_id: typing_extensions.NotRequired[typing.Optional[str]]
    """
    A unique ID for the event notification.
    """

    created_at: typing_extensions.NotRequired[str]
    """
    The timestamp that indicates when the event notification was created, in RFC 3339 format.
    """

    data: typing_extensions.NotRequired[CustomAttributeDefinitionEventDataParams]
    """
    The data associated with the event that triggered the event notification.
    """
