# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.fulfillment_state import FulfillmentState


class OrderFulfillmentUpdatedUpdateParams(typing_extensions.TypedDict):
    """
    Information about fulfillment updates.
    """

    fulfillment_uid: typing_extensions.NotRequired[typing.Optional[str]]
    """
    A unique ID that identifies the fulfillment only within this order.
    """

    old_state: typing_extensions.NotRequired[FulfillmentState]
    """
    The state of the fulfillment before the change.
    The state is not populated if the fulfillment is created with this new `Order` version.
    """

    new_state: typing_extensions.NotRequired[FulfillmentState]
    """
    The state of the fulfillment after the change. The state might be equal to `old_state` if a non-state
    field was changed on the fulfillment (such as the tracking number).
    """
