# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class QueryFilterConditionParams(typing_extensions.TypedDict):
    member: typing_extensions.NotRequired[str]
    operator: typing_extensions.NotRequired[str]
    values: typing_extensions.NotRequired[typing.Sequence[str]]
