# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .refund_created_event_object import RefundCreatedEventObjectParams


class RefundCreatedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the affected object’s type, `"refund"`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the affected refund.
    """

    object: typing_extensions.NotRequired[RefundCreatedEventObjectParams]
    """
    An object containing the created refund.
    """
