# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .error import ErrorParams
from .transfer_order import TransferOrderParams


class SearchTransferOrdersResponseParams(typing_extensions.TypedDict):
    """
    Response for searching transfer orders
    """

    transfer_orders: typing_extensions.NotRequired[typing.Sequence[TransferOrderParams]]
    """
    List of transfer orders matching the search criteria
    """

    cursor: typing_extensions.NotRequired[str]
    """
    Pagination cursor for fetching the next page of results
    """

    errors: typing_extensions.NotRequired[typing.Sequence[ErrorParams]]
    """
    Any errors that occurred during the request
    """
