# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .dispute import DisputeParams
from .error import ErrorParams


class SubmitEvidenceResponseParams(typing_extensions.TypedDict):
    """
    Defines the fields in a `SubmitEvidence` response.
    """

    errors: typing_extensions.NotRequired[typing.Sequence[ErrorParams]]
    """
    Information about errors encountered during the request.
    """

    dispute: typing_extensions.NotRequired[DisputeParams]
    """
    The `Dispute` for which evidence was submitted.
    """
