# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .team_member_wage_setting_updated_event_object import TeamMemberWageSettingUpdatedEventObjectParams


class TeamMemberWageSettingUpdatedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the affected object’s type, `"wage_setting"`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the updated team member wage setting.
    """

    object: typing_extensions.NotRequired[TeamMemberWageSettingUpdatedEventObjectParams]
    """
    An object containing the updated team member wage setting.
    """
