# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .terminal_checkout_updated_event_object import TerminalCheckoutUpdatedEventObjectParams


class TerminalCheckoutUpdatedEventDataParams(typing_extensions.TypedDict):
    type: typing_extensions.NotRequired[typing.Optional[str]]
    """
    Name of the updated object’s type, `"checkout"`.
    """

    id: typing_extensions.NotRequired[str]
    """
    ID of the updated terminal checkout.
    """

    object: typing_extensions.NotRequired[TerminalCheckoutUpdatedEventObjectParams]
    """
    An object containing the updated terminal checkout
    """
