# This file was auto-generated by Fern from our API Definition.

from .catalog_object_base import CatalogObjectBase
import typing
from .catalog_product_set import CatalogProductSet
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CatalogObjectProductSet(CatalogObjectBase):
    product_set_data: typing.Optional[CatalogProductSet] = pydantic.Field(default=None)
    """
    Structured data for a `CatalogProductSet`, set for CatalogObjects of type `PRODUCT_SET`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
