# This file was auto-generated by Fern from our API Definition.

from .catalog_object_base import CatalogObjectBase
import typing
from .catalog_item_option_value import CatalogItemOptionValue
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CatalogObjectItemOptionValue(CatalogObjectBase):
    item_option_value_data: typing.Optional[CatalogItemOptionValue] = pydantic.Field(default=None)
    """
    Structured data for a `CatalogItemOptionValue`, set for CatalogObjects of type `ITEM_OPTION_VAL`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
