# This file was auto-generated by Fern from our API Definition.

from .catalog_object_base import CatalogObjectBase
import typing
from .catalog_discount import CatalogDiscount
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CatalogObjectDiscount(CatalogObjectBase):
    discount_data: typing.Optional[CatalogDiscount] = pydantic.Field(default=None)
    """
    Structured data for a `CatalogDiscount`, set for CatalogObjects of type `DISCOUNT`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
