# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .catalog_availability_period import CatalogAvailabilityPeriod
from .catalog_object_base import CatalogObjectBase


class CatalogObjectAvailabilityPeriod(CatalogObjectBase):
    availability_period_data: typing.Optional[CatalogAvailabilityPeriod] = pydantic.Field(default=None)
    """
    Structured data for a `CatalogAvailabilityPeriod`, set for CatalogObjects of type `AVAILABILITY_PERIOD`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
