# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .dispute_evidence import DisputeEvidence
from .error import Error


class CreateDisputeEvidenceTextResponse(UncheckedBaseModel):
    """
    Defines the fields in a `CreateDisputeEvidenceText` response.
    """

    errors: typing.Optional[typing.List[Error]] = pydantic.Field(default=None)
    """
    Any errors that occurred during the request.
    """

    evidence: typing.Optional[DisputeEvidence] = pydantic.Field(default=None)
    """
    The newly uploaded dispute evidence metadata.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
