# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .employee_wage import EmployeeWage
from .error import Error


class ListEmployeeWagesResponse(UncheckedBaseModel):
    """
    The response to a request for a set of `EmployeeWage` objects. The response contains
    a set of `EmployeeWage` objects.
    """

    employee_wages: typing.Optional[typing.List[EmployeeWage]] = pydantic.Field(default=None)
    """
    A page of `EmployeeWage` results.
    """

    cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    The value supplied in the subsequent request to fetch the next page
    of `EmployeeWage` results.
    """

    errors: typing.Optional[typing.List[Error]] = pydantic.Field(default=None)
    """
    Any errors that occurred during the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
