# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .loyalty_event_filter import LoyaltyEventFilter
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class LoyaltyEventQuery(UncheckedBaseModel):
    """
    Represents a query used to search for loyalty events.
    """

    filter: typing.Optional[LoyaltyEventFilter] = pydantic.Field(default=None)
    """
    The query filter criteria.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
