# This file was auto-generated by Fern from our API Definition.

import typing

ReferenceType = typing.Union[
    typing.Literal[
        "UNKNOWN_TYPE",
        "LOCATION",
        "FIRST_PARTY_INTEGRATION",
        "OAUTH_APPLICATION",
        "ONLINE_SITE",
        "ONLINE_CHECKOUT",
        "INVOICE",
        "GIFT_CARD",
        "GIFT_CARD_MARKETPLACE",
        "RECURRING_SUBSCRIPTION",
        "ONLINE_BOOKING_FLOW",
        "SQUARE_ASSISTANT",
        "CASH_LOCAL",
        "POINT_OF_SALE",
        "KIOSK",
    ],
    typing.Any,
]
