# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..requests.address import AddressParams
from ..requests.charge_request_additional_recipient import ChargeRequestAdditionalRecipientParams
from ..requests.create_order_request import CreateOrderRequestParams
from ..requests.location import LocationParams
from ..types.create_checkout_response import CreateCheckoutResponse
from ..types.create_location_response import CreateLocationResponse
from ..types.get_location_response import GetLocationResponse
from ..types.list_locations_response import ListLocationsResponse
from ..types.update_location_response import UpdateLocationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawLocationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ListLocationsResponse]:
        """
        Provides details about all of the seller's [locations](https://developer.squareup.com/docs/locations-api),
        including those with an inactive status. Locations are listed alphabetically by `name`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListLocationsResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/locations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListLocationsResponse,
                    construct_type(
                        type_=ListLocationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        location: typing.Optional[LocationParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateLocationResponse]:
        """
        Creates a [location](https://developer.squareup.com/docs/locations-api).
        Creating new locations allows for separate configuration of receipt layouts, item prices,
        and sales reports. Developers can use locations to separate sales activity through applications
        that integrate with Square from sales activity elsewhere in a seller's account.
        Locations created programmatically with the Locations API last forever and
        are visible to the seller for their own management. Therefore, ensure that
        each location has a sensible and unique name.

        Parameters
        ----------
        location : typing.Optional[LocationParams]
            The initial values of the location being created. The `name` field is required and must be unique within a seller account.
            All other fields are optional, but any information you care about for the location should be included.
            The remaining fields are automatically added based on the data from the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateLocationResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/locations",
            method="POST",
            json={
                "location": convert_and_respect_annotation_metadata(
                    object_=location, annotation=LocationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateLocationResponse,
                    construct_type(
                        type_=CreateLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, location_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GetLocationResponse]:
        """
        Retrieves details of a single location. Specify "main"
        as the location ID to retrieve details of the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).

        Parameters
        ----------
        location_id : str
            The ID of the location to retrieve. Specify the string
            "main" to return the main location.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GetLocationResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetLocationResponse,
                    construct_type(
                        type_=GetLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        location_id: str,
        *,
        location: typing.Optional[LocationParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateLocationResponse]:
        """
        Updates a [location](https://developer.squareup.com/docs/locations-api).

        Parameters
        ----------
        location_id : str
            The ID of the location to update.

        location : typing.Optional[LocationParams]
            The `Location` object with only the fields to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateLocationResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}",
            method="PUT",
            json={
                "location": convert_and_respect_annotation_metadata(
                    object_=location, annotation=LocationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateLocationResponse,
                    construct_type(
                        type_=UpdateLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def checkouts(
        self,
        location_id: str,
        *,
        idempotency_key: str,
        order: CreateOrderRequestParams,
        ask_for_shipping_address: typing.Optional[bool] = OMIT,
        merchant_support_email: typing.Optional[str] = OMIT,
        pre_populate_buyer_email: typing.Optional[str] = OMIT,
        pre_populate_shipping_address: typing.Optional[AddressParams] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        additional_recipients: typing.Optional[typing.Sequence[ChargeRequestAdditionalRecipientParams]] = OMIT,
        note: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateCheckoutResponse]:
        """
        Links a `checkoutId` to a `checkout_page_url` that customers are
        directed to in order to provide their payment information using a
        payment processing workflow hosted on connect.squareup.com.


        NOTE: The Checkout API has been updated with new features.
        For more information, see [Checkout API highlights](https://developer.squareup.com/docs/checkout-api#checkout-api-highlights).

        Parameters
        ----------
        location_id : str
            The ID of the business location to associate the checkout with.

        idempotency_key : str
            A unique string that identifies this checkout among others you have created. It can be
            any valid string but must be unique for every order sent to Square Checkout for a given location ID.

            The idempotency key is used to avoid processing the same order more than once. If you are
            unsure whether a particular checkout was created successfully, you can attempt it again with
            the same idempotency key and all the same other parameters without worrying about creating duplicates.

            You should use a random number/string generator native to the language
            you are working in to generate strings for your idempotency keys.

            For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).

        order : CreateOrderRequestParams
            The order including line items to be checked out.

        ask_for_shipping_address : typing.Optional[bool]
            If `true`, Square Checkout collects shipping information on your behalf and stores
            that information with the transaction information in the Square Seller Dashboard.

            Default: `false`.

        merchant_support_email : typing.Optional[str]
            The email address to display on the Square Checkout confirmation page
            and confirmation email that the buyer can use to contact the seller.

            If this value is not set, the confirmation page and email display the
            primary email address associated with the seller's Square account.

            Default: none; only exists if explicitly set.

        pre_populate_buyer_email : typing.Optional[str]
            If provided, the buyer's email is prepopulated on the checkout page
            as an editable text field.

            Default: none; only exists if explicitly set.

        pre_populate_shipping_address : typing.Optional[AddressParams]
            If provided, the buyer's shipping information is prepopulated on the
            checkout page as editable text fields.

            Default: none; only exists if explicitly set.

        redirect_url : typing.Optional[str]
            The URL to redirect to after the checkout is completed with `checkoutId`,
            `transactionId`, and `referenceId` appended as URL parameters. For example,
            if the provided redirect URL is `http://www.example.com/order-complete`, a
            successful transaction redirects the customer to:

            `http://www.example.com/order-complete?checkoutId=xxxxxx&amp;referenceId=xxxxxx&amp;transactionId=xxxxxx`

            If you do not provide a redirect URL, Square Checkout displays an order
            confirmation page on your behalf; however, it is strongly recommended that
            you provide a redirect URL so you can verify the transaction results and
            finalize the order through your existing/normal confirmation workflow.

            Default: none; only exists if explicitly set.

        additional_recipients : typing.Optional[typing.Sequence[ChargeRequestAdditionalRecipientParams]]
            The basic primitive of a multi-party transaction. The value is optional.
            The transaction facilitated by you can be split from here.

            If you provide this value, the `amount_money` value in your `additional_recipients` field
            cannot be more than 90% of the `total_money` calculated by Square for your order.
            The `location_id` must be a valid seller location where the checkout is occurring.

            This field requires `PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS` OAuth permission.

            This field is currently not supported in the Square Sandbox.

        note : typing.Optional[str]
            An optional note to associate with the `checkout` object.

            This value cannot exceed 60 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateCheckoutResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}/checkouts",
            method="POST",
            json={
                "idempotency_key": idempotency_key,
                "order": convert_and_respect_annotation_metadata(
                    object_=order, annotation=CreateOrderRequestParams, direction="write"
                ),
                "ask_for_shipping_address": ask_for_shipping_address,
                "merchant_support_email": merchant_support_email,
                "pre_populate_buyer_email": pre_populate_buyer_email,
                "pre_populate_shipping_address": convert_and_respect_annotation_metadata(
                    object_=pre_populate_shipping_address, annotation=AddressParams, direction="write"
                ),
                "redirect_url": redirect_url,
                "additional_recipients": convert_and_respect_annotation_metadata(
                    object_=additional_recipients,
                    annotation=typing.Sequence[ChargeRequestAdditionalRecipientParams],
                    direction="write",
                ),
                "note": note,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCheckoutResponse,
                    construct_type(
                        type_=CreateCheckoutResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawLocationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListLocationsResponse]:
        """
        Provides details about all of the seller's [locations](https://developer.squareup.com/docs/locations-api),
        including those with an inactive status. Locations are listed alphabetically by `name`.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListLocationsResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/locations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListLocationsResponse,
                    construct_type(
                        type_=ListLocationsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        location: typing.Optional[LocationParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateLocationResponse]:
        """
        Creates a [location](https://developer.squareup.com/docs/locations-api).
        Creating new locations allows for separate configuration of receipt layouts, item prices,
        and sales reports. Developers can use locations to separate sales activity through applications
        that integrate with Square from sales activity elsewhere in a seller's account.
        Locations created programmatically with the Locations API last forever and
        are visible to the seller for their own management. Therefore, ensure that
        each location has a sensible and unique name.

        Parameters
        ----------
        location : typing.Optional[LocationParams]
            The initial values of the location being created. The `name` field is required and must be unique within a seller account.
            All other fields are optional, but any information you care about for the location should be included.
            The remaining fields are automatically added based on the data from the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateLocationResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/locations",
            method="POST",
            json={
                "location": convert_and_respect_annotation_metadata(
                    object_=location, annotation=LocationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateLocationResponse,
                    construct_type(
                        type_=CreateLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, location_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GetLocationResponse]:
        """
        Retrieves details of a single location. Specify "main"
        as the location ID to retrieve details of the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).

        Parameters
        ----------
        location_id : str
            The ID of the location to retrieve. Specify the string
            "main" to return the main location.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GetLocationResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GetLocationResponse,
                    construct_type(
                        type_=GetLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        location_id: str,
        *,
        location: typing.Optional[LocationParams] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateLocationResponse]:
        """
        Updates a [location](https://developer.squareup.com/docs/locations-api).

        Parameters
        ----------
        location_id : str
            The ID of the location to update.

        location : typing.Optional[LocationParams]
            The `Location` object with only the fields to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateLocationResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}",
            method="PUT",
            json={
                "location": convert_and_respect_annotation_metadata(
                    object_=location, annotation=LocationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateLocationResponse,
                    construct_type(
                        type_=UpdateLocationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def checkouts(
        self,
        location_id: str,
        *,
        idempotency_key: str,
        order: CreateOrderRequestParams,
        ask_for_shipping_address: typing.Optional[bool] = OMIT,
        merchant_support_email: typing.Optional[str] = OMIT,
        pre_populate_buyer_email: typing.Optional[str] = OMIT,
        pre_populate_shipping_address: typing.Optional[AddressParams] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        additional_recipients: typing.Optional[typing.Sequence[ChargeRequestAdditionalRecipientParams]] = OMIT,
        note: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateCheckoutResponse]:
        """
        Links a `checkoutId` to a `checkout_page_url` that customers are
        directed to in order to provide their payment information using a
        payment processing workflow hosted on connect.squareup.com.


        NOTE: The Checkout API has been updated with new features.
        For more information, see [Checkout API highlights](https://developer.squareup.com/docs/checkout-api#checkout-api-highlights).

        Parameters
        ----------
        location_id : str
            The ID of the business location to associate the checkout with.

        idempotency_key : str
            A unique string that identifies this checkout among others you have created. It can be
            any valid string but must be unique for every order sent to Square Checkout for a given location ID.

            The idempotency key is used to avoid processing the same order more than once. If you are
            unsure whether a particular checkout was created successfully, you can attempt it again with
            the same idempotency key and all the same other parameters without worrying about creating duplicates.

            You should use a random number/string generator native to the language
            you are working in to generate strings for your idempotency keys.

            For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).

        order : CreateOrderRequestParams
            The order including line items to be checked out.

        ask_for_shipping_address : typing.Optional[bool]
            If `true`, Square Checkout collects shipping information on your behalf and stores
            that information with the transaction information in the Square Seller Dashboard.

            Default: `false`.

        merchant_support_email : typing.Optional[str]
            The email address to display on the Square Checkout confirmation page
            and confirmation email that the buyer can use to contact the seller.

            If this value is not set, the confirmation page and email display the
            primary email address associated with the seller's Square account.

            Default: none; only exists if explicitly set.

        pre_populate_buyer_email : typing.Optional[str]
            If provided, the buyer's email is prepopulated on the checkout page
            as an editable text field.

            Default: none; only exists if explicitly set.

        pre_populate_shipping_address : typing.Optional[AddressParams]
            If provided, the buyer's shipping information is prepopulated on the
            checkout page as editable text fields.

            Default: none; only exists if explicitly set.

        redirect_url : typing.Optional[str]
            The URL to redirect to after the checkout is completed with `checkoutId`,
            `transactionId`, and `referenceId` appended as URL parameters. For example,
            if the provided redirect URL is `http://www.example.com/order-complete`, a
            successful transaction redirects the customer to:

            `http://www.example.com/order-complete?checkoutId=xxxxxx&amp;referenceId=xxxxxx&amp;transactionId=xxxxxx`

            If you do not provide a redirect URL, Square Checkout displays an order
            confirmation page on your behalf; however, it is strongly recommended that
            you provide a redirect URL so you can verify the transaction results and
            finalize the order through your existing/normal confirmation workflow.

            Default: none; only exists if explicitly set.

        additional_recipients : typing.Optional[typing.Sequence[ChargeRequestAdditionalRecipientParams]]
            The basic primitive of a multi-party transaction. The value is optional.
            The transaction facilitated by you can be split from here.

            If you provide this value, the `amount_money` value in your `additional_recipients` field
            cannot be more than 90% of the `total_money` calculated by Square for your order.
            The `location_id` must be a valid seller location where the checkout is occurring.

            This field requires `PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS` OAuth permission.

            This field is currently not supported in the Square Sandbox.

        note : typing.Optional[str]
            An optional note to associate with the `checkout` object.

            This value cannot exceed 60 characters.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateCheckoutResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/locations/{jsonable_encoder(location_id)}/checkouts",
            method="POST",
            json={
                "idempotency_key": idempotency_key,
                "order": convert_and_respect_annotation_metadata(
                    object_=order, annotation=CreateOrderRequestParams, direction="write"
                ),
                "ask_for_shipping_address": ask_for_shipping_address,
                "merchant_support_email": merchant_support_email,
                "pre_populate_buyer_email": pre_populate_buyer_email,
                "pre_populate_shipping_address": convert_and_respect_annotation_metadata(
                    object_=pre_populate_shipping_address, annotation=AddressParams, direction="write"
                ),
                "redirect_url": redirect_url,
                "additional_recipients": convert_and_respect_annotation_metadata(
                    object_=additional_recipients,
                    annotation=typing.Sequence[ChargeRequestAdditionalRecipientParams],
                    direction="write",
                ),
                "note": note,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateCheckoutResponse,
                    construct_type(
                        type_=CreateCheckoutResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
